user can search for recipes
connievi/Recipeopedia pull request #17
Opened 2022-07-08 22:41 UTC by connievi

2022-07-11 15:52 UTC, ericacooksey commented on app/src/main/java/com/example/recipeopedia/RecipeAdapter.java
>      Context context;
my bad for not catching this earlier. you do not want to save a context reference as [it can lead to leaks](https://medium.com/swlh/context-and-memory-leaks-in-android-82a39ed33002). You can pass it into the constructor, but don't save it as a field. In your onClick further down code, replace the context reference with the view's context - `v.getContext()`

2022-07-11 16:00 UTC, ericacooksey requested changes

2022-07-11 16:00 UTC, ericacooksey commented on app/src/main/java/com/example/recipeopedia/RecipeAdapter.java
> +        return null;
i'm confused here since this is the only method for Filterable interface but you're essentially leaving it unimplemented, is this just a placeholder?

2022-07-11 16:00 UTC, ericacooksey commented on app/src/main/java/com/example/recipeopedia/activities/MainActivity.java
> +    protected RecipeAdapter adapter;
`protected` means that subclasses can access this method, i'm assuming that you don't intend for MainActivity to be subclassed? so probably just make this private

2022-07-11 16:00 UTC, ericacooksey commented on app/src/main/java/com/example/recipeopedia/activities/MainActivity.java
>                  fragment = new RecipeListFragment();
i think i mentioned this before, but you don't want a default case that just returns some arbitrary fragment for an unknown ID. delete the default block. if that breaks your code, then something else is amiss

2022-07-11 16:00 UTC, ericacooksey commented on app/src/main/java/com/example/recipeopedia/fragments/RecipeListFragment.java
> +            if (recipe.getRecipeName().toLowerCase().contains(text.toLowerCase())) {
why do you need to filter manually if you're supplying a query term to the API?

2022-07-11 16:01 UTC, ericacooksey commented
I am mainly requesting changes regarding the filtering logic

2022-07-12 17:06 UTC, connievi commented on app/src/main/java/com/example/recipeopedia/RecipeAdapter.java
> +        return null;
i think i was going to use the Filterable interface but decided not to and forgot to erase that part of my code!

2022-07-13 14:23 UTC, ericacooksey approved these changes
Looks good, just take care of that one liner

2022-07-13 14:23 UTC, ericacooksey commented on app/src/main/java/com/example/recipeopedia/RecipeAdapter.java
> +    private Context context;
delete the context reference before landing - you can pass the context into the constructor, just don't save it to a field

2022-07-13 14:26 UTC, ericacooksey commented on app/src/main/java/com/example/recipeopedia/models/Recipe.java
> +    public String formatString(String text){
what's the gist of this method, is there nested json data that you're re-formatting?

2022-07-13 16:30 UTC, connievi commented on app/src/main/java/com/example/recipeopedia/models/Recipe.java
> +    public String formatString(String text){
yes it formats the nested JSON data that ingredients, instructions, and other values are stored in but i still have to make edits to this method later!

2022-07-13 16:41 UTC, merged